### ISSUE TITLE
revive loopback4-starter

### ISSUE THREAD

**Issue by shubhamp-sf** [sourcefuse/loopback4-starter#118]
**Is your feature request related to a problem? Please describe.**
This hasn't been maintained since 2021.

**Describe the solution you'd like**
Being the second most starred repo by sourceloop, this should be actively maintained by the team. Also the opened issues needs to be addressed.

**Describe alternatives you've considered**
__

**Additional context**
__

**Comment by ArslanAmeer** [comment]
@shubhamp-sf :

Please update and revive single tenant start app as well.

**Comment by shubhamp-sf** [comment]
> @shubhamp-sf :
> 
> Please update and revive single tenant start app as well.

@yeshamavani ^
