### ISSUE TITLE
Cant seem to run repo. 

### ISSUE THREAD

**Issue by vikramkh** [sourcefuse/loopback4-starter#2]
After downloading the repo, it won't run, giving me the errors:

![image](https://user-images.githubusercontent.com/22332387/58790713-e8f28880-85be-11e9-968b-bc0457ad1612.png)

OK I FIXED THIS BY PLACING OAUTH before the 2 but now I am getting 

![image](https://user-images.githubusercontent.com/22332387/58793056-56a0b380-85c3-11e9-95e7-ed1a26bac1ef.png)
Ok I fixed this by adding Oauth before the Client.

**Comment by vikramkh** [comment]
See Updates for fix

**Comment by samarpan-b** [comment]
These errors come when your compilation doesn't happen properly. If you face such issue again just remove the 'dist' folder and run 
`npm run build`
