### ISSUE TITLE
database needs to be changed to db

### ISSUE THREAD

**Issue by kjellouli** [sourcefuse/loopback4-starter#32]
Can't connect to redis, it results in ERR invalid db index. database in redis.datasource.ts needs to be changed to db in line:

https://github.com/sourcefuse/loopback4-starter/blob/e76d8d70f2484fb082204efa8431d3789436e8fd/src/datasources/redis.datasource.ts#L17

as per:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f574f4aa1344774ef08caf8c9e2f994c4e7fa30e/types/ioredis/index.d.ts#L948

**Comment by samarpan-b** [comment]
Thanks for the update @kjellouli . Would you mind raising a PR for this ? I can merge it then.

**Comment by kjellouli** [comment]
https://github.com/sourcefuse/loopback4-starter/pull/34

**Comment by samarpan-b** [comment]
Merged
