### ISSUE TITLE
Question: Removing Redis/Putting Redis in the Cloud

### ISSUE THREAD

**Issue by vikramkh** [sourcefuse/loopback4-starter#35]
I uploaded my git to the cloud but can't seem to get the redis part working. I've tried opening an elasticache instance on aws as well as connecting to my local redis server from the ec2 running my application. Both seem to fail, so I was wondering if it's possible to remove redis altogether without affecting the latency/functionality of the app. Also.. in the loopback4 docs, it seems to show redis without a url:
https://loopback.io/doc/en/lb4/Repositories.html
I was wondering if this had anything to do with why I couldnt connect to the cloud redis?

**Comment by samarpanB** [comment]
Can you please share how you are giving the redis configuration?

**Comment by vikramkh** [comment]
So sorry, I was finally able to get it to work by downloading and running redis locally on the Elastic Beanstalk EC2 instance rather than in ElasticCache on AWS.
