### ISSUE TITLE
usersId not found

### ISSUE THREAD

**Issue by temp3l** [sourcefuse/loopback4-starter#36]
kept getting errors about usersId not found

added this in **src/models/user-credentials.model.ts** to make it run

```js
  @property({
    type: 'number',
  })
  user_id?: number;
```

**Comment by jessevanmuijden** [comment]
i had the same issue, but it appeared that i had not fully run all migrations.

**Comment by samarpan-b** [comment]
Closing it. This should not be an issue anymore.
