### ISSUE TITLE
Initial authorization

### ISSUE THREAD

**Issue by vikramkh** [sourcefuse/loopback4-starter#4]
Not a bug, but just wondering why everything requires bearer authentication? How do you get the initial token then?

**Comment by samarpan-b** [comment]
Hello @vikramkh ,

Have a look at the login APIs defined here - https://github.com/sourcefuse/loopback4-starter/blob/master/src/modules/auth/login.controller.ts

They do not require bearer token. They use different strategy. Check it out.

**Comment by vikramkh** [comment]
Thanks so much!
