### ISSUE TITLE
Login not work

### ISSUE THREAD

**Issue by ggmac23** [sourcefuse/loopback4-starter#42]
I install the demo everything work fine, but when i try to login from the explorer it response with this error: 

**To Reproduce**
1. Go to http://[::1]:3000/explorer/#/LoginController/LoginController.login
2. POST /auth/login
3. Send : 
{
  "client_id": "webapp",
  "client_secret": "saqw21!@",
  "username": "super_admin",
  "password": "test123!@#"
}
4. See error: 
{
  "error": {
    "statusCode": 401,
    "name": "UnauthorizedError",
    "message": {
      "name": "error",
      "length": 119,
      "severity": "ERROR",
      "code": "42P01",
      "position": "194",
      "file": "parse_relation.c",
      "line": "1173",
      "routine": "parserOpenTable"
    }
  }
}

Can you help me?

**Comment by fgvicente** [comment]
Hi. could you solve it I have the same problem

**Comment by samarpanB** [comment]
It seems to be error with migration scripts. Let me check that. Give me some time. Meanwhile, can you please confirm if you have run the migration scripts alright?

**Comment by fgvicente** [comment]
Thanks @samarpanB  ... the migrate had run badly

**Comment by samarpan-b** [comment]
This should have been fixed with latest updates. Closing it hence.

**Comment by personwholearn** [comment]
I have the same issue right now with the last update! , please help me 
the error 
{
"error": {
"statusCode": 401,
"name": "UnauthorizedError",
"message": {
"name": "error",
"length": 185,
"severity": "ERROR",
"code": "42P01",
"position": "194",
"file": "d:\pginstaller_12.auto\postgres.windows-x64\src\backend\parser\parse_relation.c",
"line": "1173",
"routine": "parserOpenTable"
}
}
}

**Comment by samarpanB** [comment]
Can you please check if you have run all the migration scripts?

**Comment by personwholearn** [comment]
@samarpanB  thanks for your response :) yes i checked many times in DB, i followed your steps and , ( i clone your project  -> npm i -> change .env ->
db-migrate up -> npm start ) and i go to "login/auth" and enter
{
"client_id": "webapp",
"client_secret": "saqw21!@",
"username": "super_admin",
"password": "test123!@#"
}

![Screenshot (158)](https://user-images.githubusercontent.com/65703670/87989862-152ed880-cae3-11ea-8007-32815712e05f.png)

but the error still 

"error": {
"statusCode": 401,
"name": "UnauthorizedError",
"message": {
"name": "error",
"length": 185,
"severity": "ERROR",
"code": "42P01",
"position": "194",
"file": "d:\pginstaller_12.auto\postgres.windows-x64\src\backend\parser\parse_relation.c",
"line": "1173",
"routine": "parserOpenTable"
}
}
}

![Screenshot (159)](https://user-images.githubusercontent.com/65703670/87990336-190f2a80-cae4-11ea-95c0-984fc32423f0.png)

**Comment by personwholearn** [comment]
i also changes postgresdb 12 to 10 , i also update the project whether "`lb4 rest-crud `"or `npm update` ,i made many `db-migrate up` and `db-migrate down` but still in the same issue , i used windows 10 ,npm -v is 6.14.6 ,node -v is v12.18.0
please help me😭😭😭🤯🤯

**Comment by personwholearn** [comment]
can anyone help me ?

**Comment by samarpan-b** [comment]
Can you share your .env ? Hide the DB host and password from there.

**Comment by personwholearn** [comment]
NODE_ENV=
LOG_LEVEL=
DB_HOST=localhost
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=123
DB_DATABASE=postgres
DB_SCHEMA=postgres
REDIS_HOST=
REDIS_PORT=
REDIS_URL=
REDIS_PASSWORD=
REDIS_DATABASE=0
JWT_SECRET=
JWT_ISSUER=
AUDIT_SCHEMA=
USER_TEMP_PASSWORD=
GOOGLE_AUTH_URL=
GOOGLE_AUTH_CLIENT_ID=
GOOGLE_AUTH_CLIENT_SECRET=
GOOGLE_AUTH_TOKEN_URL=
GOOGLE_AUTH_CALLBACK_URL=

**Comment by personwholearn** [comment]
we solved in the ticket of https://github.com/sourcefuse/loopback4-starter/issues/54
