### ISSUE TITLE
[Question] How to define belongs to user relationship when creating a component?

### ISSUE THREAD

**Issue by pbalan** [sourcefuse/loopback4-starter#47]
Hi,

I'd like to develop my application logic as components and use this as the base application.

I'm not clear about how I can inject the user into the component especially when using a user-modifiable entity as the abstract class.

Could you please provide me a direction on it?

**Comment by samarpan-b** [comment]
You can get all injectables from application instance from within your component.

`    @inject(CoreBindings.APPLICATION_INSTANCE)
    private readonly application: RestApplication,`

For example, here I am trying to get a datasource from the application instance

`const redisDS = (await this.application.get(
        `datasources.${this.config.name}`,
      )) as juggler.DataSource;`

**Comment by samarpan-b** [comment]
@pbalan can I close this issue now ?
