### ISSUE TITLE
Audit-log model bug

### ISSUE THREAD

**Issue by SFIN571** [sourcefuse/loopback4-starter#5]
**Describe the bug**
Error while fetching user data. 

**To Reproduce**
1. Create a '/me' api which returns user data.
2. This should break the application giving an error

**Screenshots**
![starter_bug](https://user-images.githubusercontent.com/51310882/58870042-03bb1f00-86dd-11e9-8586-fba897ffb59d.PNG)

**Comment by vikramkh** [comment]
Did you set your redis database = 0?

**Comment by SFIN571** [comment]
Yes, i did. The redis part is working fine (I am not sure why this warning appears).

**Comment by SFIN571** [comment]
Actually the error is in audit-log model. A field that should be named 'operation_time' is specified as 'operation_type'. Doing this small change will solve the issue. But this particular action does not create audit, so why is this even hitting a query in this 'audit_log' table?

**Comment by samarpan-b** [comment]
Fixed the issue in above PR. Please update your cloned environments accordingly.
