### ISSUE TITLE
Re run db: migrate

### ISSUE THREAD

**Issue by vikramkh** [sourcefuse/loopback4-starter#6]
How do I re run db: migrate? I changed the sql files and wanted to re run migrate but it just says nothing to migrate. I emptied my database and it still wont migrate, it just says No migrations to run.
![image](https://user-images.githubusercontent.com/22332387/58921324-1268fc80-8704-11e9-8f46-c4e8146b9a8b.png)

**Comment by vikramkh** [comment]
I realized now I should have used reset, but now that the table is gone, how do I re run migrate, because if I try reset now, it will tell me that the schema does not exist, but migrate will say that no migrations to run

**Comment by vikramkh** [comment]
Ok not sure how but I figured it out. However, is lbstarter.dbs being used? I tried to add my own code to the sql files but was getting errors and I wasn't sure if I needed to modify somewhere else to fit the new tables that I was adding in?

**Comment by samarpan-b** [comment]
@vikramkh 
Few things to note here -
1. I need to improve documentation further describing how to manage db migrations.
2. The best way to ensure db migrations work perfectly fine is -  **never update existing migrations which are already run**. For any changes to DB tables or data, just create a new migration file using [db-migrate cli](https://db-migrate.readthedocs.io/en/latest/Getting%20Started/usage/#creating-migrations). This will create 3 files - one js in _/migrations_ and 2 sql files inside _/migrations/sqls_. You can write your own alter scripts here for any modification you need. As the project progresses, you may need to update your DB again, you should repeat the same step - create new migration everytime.
3. If there is still utmost need to change existing migrations, say there was a small error in some script, there is a simple workaround. Just go to public schema in database. There will be a _migrations_ table. Check all the entries in this table. db-migrate reads this table to know which all migrations have been run. Refer docs [here](https://db-migrate.readthedocs.io/en/latest/Getting%20Started/usage/#running-migrations). So, whichever script you changed, just delete that file entry from this table. Run `npm run db:migrate` again. It will work.
4. If you want to just reset the database to empty state, then run `npm run db:migrate:reset`. It will run all your down scripts in reverse order and will empty its own table '_migrations_' in DB.
5. If you want to just go down one version only, then run `npm run db:migrate:down`. It will run the last down script and remove it from _migrations_ table.

Please have a read at the documentation of [db-migrate](https://db-migrate.readthedocs.io/en/latest/) to learn about how useful this tool is for handling db migrations and versioning.

**Comment by samarpan-b** [comment]
> Ok not sure how but I figured it out. However, is lbstarter.dbs being used? I tried to add my own code to the sql files but was getting errors and I wasn't sure if I needed to modify somewhere else to fit the new tables that I was adding in?

lbstarter.dbs is the project file for [DbSchema](https://www.dbschema.com/) tool that we have used to create Entity-relationship diagram for the database and execute it into database directly. It helps in keeping the DB schema intact, up to date and easily shareable. It can also be used to extract DB scripts out of it for  migrations sqls.

Hope this helps.

**Comment by vikramkh** [comment]
Thanks so much for the help!

**Comment by argupta23** [comment]
> 
> 
> > Ok not sure how but I figured it out. However, is lbstarter.dbs being used? I tried to add my own code to the sql files but was getting errors and I wasn't sure if I needed to modify somewhere else to fit the new tables that I was adding in?
> 
> lbstarter.dbs is the project file for [DbSchema](https://www.dbschema.com/) tool that we have used to create Entity-relationship diagram for the database and execute it into database directly. It helps in keeping the DB schema intact, up to date and easily shareable. It can also be used to extract DB scripts out of it for migrations sqls.
> 
> Install DbSchema and open this file there. You will see the entire ERD.
> 
> Hope this helps.

@samarpan-b
Is there a mongodb version of the schema available that you could share or steps on how to convert the postgres version to mongodb are also welcome?

Thanks

**Comment by samarpan-b** [comment]
@argupta23 I don't have a mongodb version available right now. I'll need some time to provide you for that.  I'll try next week.

If you are able to do it before that, feel free to contribute with a PR.
