### ISSUE TITLE
User Tenant Belongs To relations returning undefined

### ISSUE THREAD

**Issue by Hairlock** [sourcefuse/loopback4-starter#60]
I'm running into an issue when making use of the userTenantRepo's belongsTo functions. The role, user and tenant properties are returning undefined when called with the userTenant's id. 

The following are rows in my user_tenants and roles table. The user is super_admin

![image](https://user-images.githubusercontent.com/2579054/90959046-f760e480-e48f-11ea-99bf-4381151221a2.png)

![image](https://user-images.githubusercontent.com/2579054/90959041-eb752280-e48f-11ea-8d97-41ea17fe73f9.png)

The code for the user_tenant model and repository are unchanged, same with the role model and repo.

Any advice would be appreciated, thanks.

**Comment by samarpan-b** [comment]
Hi @Hairlock I hope you got your issue resolved. Can you please help others by explaining how was it resolved ?
