### ISSUE TITLE
Question: Alternatives to Redis

### ISSUE THREAD

**Issue by Sheldonfrith** [sourcefuse/loopback4-starter#61]
I'm new to all this so bear with me.
Just wondering why this project uses Redis to store revoked tokens, instead of the main SQL database?
When implementing LB4 with auth for my apps I would prefer to only have to set up and manage one database, especially since I am completely unfamiliar with Redis.
Has anyone implemented this project, or something similar, without Redis? How did you do it?

Thanks!

**Comment by samarpan-b** [comment]
Redis is only used to store revoked tokens and refresh tokens. Revoked tokens are added to redis when user logs out.

**Comment by Sheldonfrith** [comment]
Yes, I understand that, just wondering WHY (as opposed to just using the main database to store revoked tokens). Thanks.

**Comment by samarpan-b** [comment]
For performance @Sheldonfrith and also to avoid load on DB, as this would happen for every request.

**Comment by Sheldonfrith** [comment]
Thank you! That answers my question.
