### ISSUE TITLE
A single connection pool

### ISSUE THREAD

**Issue by mbnoimi** [sourcefuse/loopback4-starter#70]
Does this starter boilerplate support a single connection pool per app?
I don't want to create a connection pool per tenant (just want a single connection pool for multi-tenant)
In PostgreSQL usually we use a schema per tenant which means the app uses a single database with multi schemas.

**Comment by samarpan-b** [comment]
Yes its using single pool. It uses logical separation of tenant data rather than physical separation.

**Comment by mbnoimi** [comment]
> Yes its using single pool. It uses logical separation of tenant data rather than physical separation.

Thanks a lot. I'll use soon

**Comment by mbnoimi** [comment]
Did you take a look into this new example?
https://github.com/strongloop/loopback-next/tree/master/examples/multi-tenancy

**Comment by samarpan-b** [comment]
I haven't taken a look at it. This starter project was built way long ago. We just kept upgrading it to latest. This project not only gives you multi tenancy. it also guides you on a standard LB4 monolithic application architecture principles as well. In fact, we also have a branch for single tenant architecture.
